/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author rodrigo08
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnEditar = new javax.swing.JMenu();
        EditEmpleado = new javax.swing.JMenuItem();
        BtnVisualizar = new javax.swing.JMenu();
        VerEmpleados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        BtnEditar.setText("Editar");

        EditEmpleado.setText("Empleado");
        EditEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmpleadoActionPerformed(evt);
            }
        });
        BtnEditar.add(EditEmpleado);

        jMenuBar1.add(BtnEditar);

        BtnVisualizar.setText("Visualizar");

        VerEmpleados.setText("Empleados");
        VerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEmpleadosActionPerformed(evt);
            }
        });
        BtnVisualizar.add(VerEmpleados);

        jMenuBar1.add(BtnVisualizar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmpleadoActionPerformed
        
        EditarEmpleado editEmp = EditarEmpleado.getVentana(); 
        if (!jDesktopPane1.isAncestorOf(editEmp)) {
            //Si el JDesktopPane no contiene a optionFrame, este se agrega.
            jDesktopPane1.add(editEmp);
        }else{
            //Si el JDesktopPane ya contiene a optionFrame, este solo se selecciona.
            jDesktopPane1.setSelectedFrame(editEmp);
        }
        editEmp.setVisible(true);
        
    }//GEN-LAST:event_EditEmpleadoActionPerformed

    private void VerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEmpleadosActionPerformed
        TablaEmpleado ventana = TablaEmpleado.getVentana();
        if (!jDesktopPane1.isAncestorOf(ventana)) {
            //Si el JDesktopPane no contiene a optionFrame, este se agrega.
            jDesktopPane1.add(ventana);
        }else{
            //Si el JDesktopPane ya contiene a optionFrame, este solo se selecciona.
            jDesktopPane1.setSelectedFrame(ventana);
        }
        ventana.setVisible(true);
    }//GEN-LAST:event_VerEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BtnEditar;
    private javax.swing.JMenu BtnVisualizar;
    private javax.swing.JMenuItem EditEmpleado;
    private javax.swing.JMenuItem VerEmpleados;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
